### Get /currencies
GET http://localhost:8080/currencies

### Get /currency/RUB
GET http://localhost:8080/currency/RUB

### Post /currencies
POST http://localhost:8080/currencies
Content-Type: application/x-www-form-urlencoded

name=Tenge&code=KZT&sign=₸

### Get /exchangeRates
GET http://localhost:8080/exchangeRates

### Get /exchangeRate/RUBUSD
GET http://localhost:8080/exchangeRate/RUBUSD

### Post /exchangeRates/CNYUSD
POST http://localhost:8080/exchangeRates
Content-Type: application/x-www-form-urlencoded

baseCurrencyCode=CNY&targetCurrencyCode=USD&rate=0.14092

### Patch /exchangeRate/CNYUSD
PATCH http://localhost:8080/exchangeRate/CNYUSD
Content-Type: application/x-www-form-urlencoded

rate=10

### GET /exchange?from=USD&to=RUB&amount=10
GET http://localhost:8080/exchange?from=USD&to=RUB&amount=10
